name: Build TypeScript

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      #- name: Set up Node.js
      #  uses: actions/setup-node@v4
      #  with:
      #    node-version: 20

      #- name: Install TypeScript
      #  run: npm install typescript

      - name: Compile TypeScript
        run: npx tsc

      - name: Commit compiled files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Compile TypeScript files"
          git push
